import Navbar from "./components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-900 text-amber-50 bg-gradient-to-l from-[#500101] via-[#161423] to-[#23202d]
">
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
